// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SerenBot.Entities;

namespace SerenBot.Migrations
{
    [DbContext(typeof(SerenDbContext))]
    [Migration("20181217205412_Added RoleIds to guilds")]
    partial class AddedRoleIdstoguilds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SerenBot.Entities.Models.Guild", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<ulong>("AmloddRoleId");

                    b.Property<ulong>("CadarnRoleId");

                    b.Property<ulong>("CrwysRoleId");

                    b.Property<string>("GuildName");

                    b.Property<ulong>("HefinRoleId");

                    b.Property<ulong>("IorwerthRoleId");

                    b.Property<ulong>("IthellRoleId");

                    b.Property<ulong>("MeilyrRoleId");

                    b.Property<ulong>("NotificationWebhookId");

                    b.Property<string>("NotificationWebhookToken");

                    b.Property<string>("Prefix")
                        .HasMaxLength(4);

                    b.Property<ulong>("TrahaearnRoleId");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("SerenBot.Entities.Models.NotificationUser", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("NotificationValue");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("NotificationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
