# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  buildFramework: 'netcoreapp2.1'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'db1b6037-9221-4ef2-8020-bf0dd9501c3d'
    repository: 'serenbot'
    command: 'buildAndPush'
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
# - script: dotnet publish --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) -f $(buildFramework)
#   displayName: 'dotnet publish $(buildConfiguration)'
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: Container